type Mutation {
  createUsersMutation(input: UsersInput): Boolean
  updateUserMutation(id: Int!, input: UsersInput): Boolean
  removeUserMutation(id: Int!): Boolean
  signIn(input: SignInInput): UserToken
}
type Query {
  users: [Users]
  user(id: Int!): Users
  me: Users
}
input UsersInput {
  id: Int
  first_name: String
  last_name: String
  email: String
  password: String
}
type Users {
  id: Int
  first_name: String
  last_name: String
  email: String
  password: String
}
input SignInInput {
  email: String
  password: String
}

type UserToken {
  token: String!
}
